#!/bin/bash -e

function usage
{
    	echo "USAGE: $0 [-d DOJO_HOSTNAME ] [ LOCAL_PORT ]"
    	echo ""
    	echo "This script forwards port from your local machine (default: port 5542)"
    	echo "to the VNC server of the pwn.college dojo (or a custom dojo if -d is used)."
    	echo ""
    	echo "With the default port 5942, you can then connect to VNC with: "
    	echo "# vncviewer :42"
    	exit
}

DOJO=dojo.pwn.college

while getopts "d:" OPT
do
	case $OPT in
		d) DOJO=$OPTARG ;;
		*) usage ;;
	esac
done
shift $((OPTIND-1))

LOCAL_PORT=$1
case $LOCAL_PORT in
    	'') LOCAL_PORT=5942 ;;
    	*[!0-9]*) usage ;;
    	*) ;;
esac

socat tcp-listen:$LOCAL_PORT,reuseaddr exec:"ssh -v hacker@$DOJO exec socat - unix-connect\:/tmp/vnc/vnc_socket",nofork
